Development
TSHEPO-CLOUD/capstone-my-spaceship pull request #33
Opened 2021-08-05 16:19 UTC by PolinaStamenova

2021-08-05 18:30 UTC, hemant-soni-vst-au4 requested changes
Hi @PolinaStamenova and @TSHEPO-CLOUD, 

## Highlights
- Video presentation is really good. you nicely presented the feature of the project. 👍 
- Great work on meeting most of the requirements. 💯 
- Testing of counter function.

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there! 

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

- [ ] As per requirements all the members should appear in the video and talk about the project. You guys can use the zoom to meet the requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- It will be great if we provide a `live link` of the project in our `README` file.

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-05 18:30 UTC, hemant-soni-vst-au4 commented on src/createElements.js
> +    displayPopup(pokeurl);
- [ ] Let's try to add the `hover` effect on the `comment button`. When the user hovers the comment button cursor should change to the pointer. Kindly fix this issue.

2021-08-05 18:30 UTC, hemant-soni-vst-au4 commented on src/createElements.js
> +  like.classList.add('far', 'fa-heart');
- [ ] Let's try to add the `hover` effect on the `like icon`. When the user hovers the like icon cursor should change to the pointer. Kindly fix this issue.

2021-08-05 18:30 UTC, hemant-soni-vst-au4 commented on src/addComment.js
> +  btn.addEventListener('click', async () => {
- [ ] Optional
After adding the comment, the input fields are not empty. We can improve this by adding input fields as empty on the comment button event listener. Let's try to fix it.

2021-08-06 08:45 UTC, PolinaStamenova commented
https://drive.google.com/file/d/1hVAiHX4RsG-FlIej06DMjNAJBwqLNQ5Y/view?usp=sharing

2021-08-06 09:45 UTC, bellom approved these changes
## Hi @PolinaStamenova @TSHEPO-CLOUD  👏  

**Great work making all the necessary corrections from the previous review.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

### [Optional]
The reason why we do write tests is for us to be able to debug quickly and easily, that is; once anything goes wrong in our actual code, our test should fail and point to us where we have the bug. 

In your case:
we are supposed to have a `counter function`  in the codebase then we should write a jest test to test the `counter function` once the counter function is broken, the test should fail.

So you might want to work on the mocking, let's re-check [jest easy mocking](https://jestjs.io/)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-06 09:48 UTC, PolinaStamenova commented
@bellom Oluwaseun,

thank you for the review and the provided link source. 
We will check it now!

2021-08-06 09:48 UTC, merged